#!/usr/bin/env python3
"""
Convert GLB files to base64 JavaScript files for direct HTML opening.
Usage: python convert_glb_to_base64.py
"""
import base64
import os
import sys

def convert_glb_to_js(glb_path, output_path, var_name):
    """Convert a GLB file to a base64 JavaScript variable."""
    print(f"Converting {glb_path}...")
    
    if not os.path.exists(glb_path):
        print(f"Error: {glb_path} not found")
        return False
    
    # Read GLB file
    with open(glb_path, 'rb') as f:
        glb_data = f.read()
    
    print(f"  Size: {len(glb_data) / 1024 / 1024:.2f} MB")
    
    # Convert to base64
    b64_data = base64.b64encode(glb_data).decode('ascii')
    
    # Write JS file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"// Auto-generated base64 GLB data for {os.path.basename(glb_path)}\n")
        f.write(f"// DO NOT EDIT - This file is generated by convert_glb_to_base64.py\n\n")
        f.write(f"window.{var_name} = 'data:application/octet-stream;base64,{b64_data}';\n")
    
    print(f"  Output: {output_path}")
    print(f"  Variable: window.{var_name}")
    return True

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Convert old-craftsman.glb
    convert_glb_to_js(
        os.path.join(script_dir, 'assets', 'old-craftsman.glb'),
        os.path.join(script_dir, 'assets', 'old-craftsman-data.js'),
        'OLD_CRAFTSMAN_GLB_BASE64'
    )
    
    # Convert alian.glb
    convert_glb_to_js(
        os.path.join(script_dir, 'assets', 'alian.glb'),
        os.path.join(script_dir, 'assets', 'alian-data.js'),
        'ALIAN_GLB_BASE64'
    )
    
    print("\nDone! Now you can uncomment the script tags in index.html to use base64 mode.")
    print("This will allow direct HTML opening with 3D models.")
